### ISSUE TITLE
Maya 2025.1 install issue

### ISSUE THREAD

**Issue by Orkosara** [joaen/animation-retargeting-tool#11]
I follow the instruction multiple times but the script editor always gives me 

# Error: ModuleNotFoundError: file C:\Users/ASUS/Documents/maya/scripts\animation_retargeting_tool.py line 24: No module named 'shiboken2'

Any reason why this happen ?

**Comment by joaen** [comment]
Hi, it seems like newer versions of Maya 2025 is not using Shiboken2/Pyside2 anymore.

You can try to replace the lines at the top of the script:

```
from shiboken2 import wrapInstance
from PySide2 import QtCore, QtGui, QtWidgets
```

To this:

```
from shiboken6 import wrapInstance
from PySide6 import QtCore, QtGui, QtWidgets
```

**Comment by Orkosara** [comment]
Thank you. It work. I have last question. Is it possible to do workflow like this using this tool ?

Retarget animation > bake animation > import new motion > retarget animation > bake animation again in same scene > repeat the process.  

Thanks

**Comment by joaen** [comment]
Glad you got it working.

Yes, you can create all the connections between the rig and skeleton. Save that file as your "master file".

Then you just can just open your master file and import the animation. So you don't have to recreate the connections every time.
